### ISSUE TITLE
Error: Only got short reply

### ISSUE THREAD

**Issue by Sineos** [jangxx/node-magichome#20]
I would like to `turnOn` a LED stripe and immediately query the current state. With the code below, I'm facing a strange issue:

- Without the `sleeper` function the returned color values are wrong. I guess this is nothing special as the controller has a "fancy startup animation" (although they are wrong as well when the light already is on)
- With values around 500ms for the `sleeper`, I reproducible get a:
```
>node test.js
Received: f0 71 23 84
error: Only got short reply
```
- With values significantly below (e.g. 0ms, 200ms etc) or over 500ms (e.g. 600ms+) the error is not observed
- Maybe also noteworthy: With the short delays, the returned `type` is always 113, with the 600+ delays the `type` is 4

I'm I doing something wrong? I would appreciate if you could shed some light into this behavior.

```javascript
const MagicHomeControl = require('magic-home').Control;
const ip = '192.168.178.74';
const controlOptions = {log_all_received: true, ack: {power: false, color: false, pattern: false, custom_pattern: false}};
const lampControl = new MagicHomeControl(ip, controlOptions);

const sleeper = function (ms) {
	const promise = new Promise(((resolve, reject) => {
		setTimeout(() => {
			resolve();
		}, ms);
	}));
	return promise;
};

lampControl.turnOn()
	.then(() => sleeper(500))
	.then(() => lampControl.queryState())
	.then(state => console.log('\n' + JSON.stringify(state) + '\n'))
	.catch(err => console.log('error: ' + err.message));
```

**Comment by jangxx** [comment]
What you are seeing is a mix-up of answers from the `turnOn` and the `query` call. Apparently your controller is acknowledging the `turnOn` command but you set `ack: { power: false }`, which causes the library to not wait for a response from the controller and immediately sending the query command afterwards. Unfortunately, the controller does not correlate the responses in any way, so when the controller sends `f0 71 23 84` as acknowledgement for the turnOn, the data is passed to the handler for the query command, since it is set up to expect a reply. After sending the acknowledgement, the controller now sends the response to the query command. Since not all controllers send the full response in one packet, a timeout of 500ms is used to wait for all the data the controller might send. This leads to the situation, where the query handler receives a buffer like `f0 71 23 84 <actual query response>`, so the bytes read out of the buffer are just gibberish. The type field for example, is the byte at position 2, so `0x71` in this case, which corresponds to 113 in decimal. I could fix this in the library, by making sure that the first byte of the query is always correct and that the buffer has exactly the correct length, but that wouldn't really improve anything, except for an additional error message.

To cut a long story short: Simply set `ack: { power: true }` while leaving the rest as false and everything should work as expected and without the sleeper.

**Comment by Sineos** [comment]
Many thanks for the detailed explanation. 👍 
In fact, setting `ack: { power: true }` does improve the situation. Maybe my controller, but immediately querying the state after power on yields:

```
>node test.js
Received: f0 71 24 85
Received: 81 04 24 61 01 1c ff ff 00 00 05 00 f0 1a

{"type":4,"on":false,"mode":"color","speed":10,"color":{"red":255,"green":255,"blue":0},"warm_white":0,"cold_white":0}
```
Here the colors are reported correct, but the `on` state is wrong. Introducing a 200ms delay (100 ms is too short) with the sleeper brings correct results:
```
>node test.js
Received: f0 71 24 85
Received: 81 04 23 61 01 1c ff ff 00 00 05 00 f0 19

{"type":4,"on":true,"mode":"color","speed":10,"color":{"red":255,"green":255,"blue":0},"warm_white":0,"cold_white":0}
```

Anyway, thanks a lot for this module and your support!

**Comment by jangxx** [comment]
That is definitely something with your controller and the startup animation, and not something this library could fix. Using a delay seems like a sensible workaround, so I guess we can close this.
