### ISSUE TITLE
custom_mode_test.js doesn't work with WS2812b

### ISSUE THREAD

**Issue by MrVinceZ** [jangxx/node-magichome#28]
Hello,

First of all, sorry if my english is poor.

I just clone this repo to use it with my LED and I juste try the custom_node_test.js and nothing happen on my strip

`test@nas:~/node_modules/magic-home/examples# node custom_mode_test.js 192.168.0.96
success`

If I try to use effect_test.js it work fine !

In my MagicHome App I have a custom mode 
"Overlay from end to start" but it loop and I want to make it once, after that, I want it to be just on. 
So I add a "Change quickly" step with the same Start Color & End Color but unfortunately, I can't set the speed to 0, so the two steps loop every minutes. 
I assume that I can remake this with a custom_mode but for now, nothing happen when I launch the custom_mode_test.js

Do I forgot something ? 

Thank you for reading me

**Comment by jangxx** [comment]
The whole custom mode stuff only works with regular LED strips for now. If you want to take a crack at implementing some sort of `IACustomMode` feel free to do so. Otherwise, unless I buy one of those WS2812B supporting controller, or someone sends me some cleaned up network traces with annotations, or you can point me to another library which actually supports this feature, I don't see it happening soon.

Also, to address your original problem, I don't think you can solve it with a custom mode created by this library or any library. "Custom" only refers to "user created" in this context and since this library has to use the same interface/protocol as the app, I'm pretty sure it can't do stuff you can't do in the app already.

I would recommend to take a look at some alternative controller firmware like [Tasmota](https://github.com/arendst/Tasmota), or [ESPurna](https://github.com/xoseperez/espurna), which might be able to help you achieve your desired effect.

**Comment by MrVinceZ** [comment]
It's possible to set the speed at 0%, but not in the App, I think it's an issue with the min_value of the slider set to 1%.

So, I can't call a function create inside the app ? Or create manually a function ?

**Comment by MrVinceZ** [comment]
(When I say "function" I'm talking about the custom preset)

**Comment by jangxx** [comment]
The controllers do not seem to actually store the created presets themselves. The preset is only stored within the app and when you tap on it, all the necessary information is sent to the controller in that moment. You can therefore neither "download" the stored presets from the controller, nor trigger them from some other place than the app itself, since it's not stored anywhere on the controller. That's how the custom patterns for regular LED strips work at least and I'm pretty sure the individually addressable ones are no different, since it's pretty much the same protocol after all.

All that doesn't change the fact, that even if you set a speed value of 0 with this library, the value being sent to the controller is not actually 0 but 1, since 0 doesn't make any sense. The individually addressable patterns are different, in that you can apparently send a value of 0, but I have no idea how the controller reacts to that, since I don't have one. My guess is, that the controller simply does nothing or it plays the pattern at an even lower speed, but the pattern certainly does not stand still with a speed value of 0.

**Comment by MrVinceZ** [comment]
If I create and enable a preset with the app, and then I use the cmd `magic-home on [IP]`, the controller use the preset, without the application

I will make some test with the speed, and other things like that

**Comment by jangxx** [comment]
That only works because the controller remembers it's last setting when put into standby. If you cut the power however, I'm pretty sure it would not remember your custom setting and even if it did, it still would not store more than a single one, i.e. the last one that was used. But hey, knock yourself out, maybe out figure out something new. Like I said, I don't have one of these controllers, so anything is possible (but not very likely).
