### ISSUE TITLE
Requests fail after first request

### ISSUE THREAD

**Issue by znepb** [jangxx/node-magichome#29]
I've just discovered this and decided to try it out with my AK001-ZJ210. My lights only accept one request before refusing to serve anymore. The issue is resolved when the application is restarted. I don't know if there's something I'm missing, as I am pretty new to node.js. Any help is appreciated!

**Comment by jangxx** [comment]
I've lost count of the number of people with this same problem, so I've created a wiki page to explain it better: https://github.com/jangxx/node-magichome/wiki/Understanding-the-ack-parameter

Also, version 2.6.0 should now raise an error (i.e. reject the promise) instead of silently getting stuck, to make it clearer what's actually happening.
