### ISSUE TITLE
Feature Request: Brightness

### ISSUE THREAD

**Issue by 0rTiN** [jangxx/node-magichome#31]
Hi,
any chance to get a command to set brightness like: `magic-home setbright|bright <IP>`

**Comment by jangxx** [comment]
This is unfortunately not really possible, since there is no way to set the brightness directly. The brightness method `setColorWithBrightness` is simply a convenience method, which scales the color values, and you can easily do that yourself by simply multiplying your color values with the brightness between 0 and 1.

For example: `magic-home color <ip> 127 0 0` to set the controller to red at 50% brightness.

A standalone brightness command would require a `queryState` to get the current color from the controller and then a call to set the color. This would of course be possible, but kind of out of scope for the CLI tool, which is only really made for exposing the raw library methods and not a fully fledged command line interface to conveniently control your controllers.

Using `jq` you could have a bash oneliner like this however:

    magic-home color <ip> $(magic-home query <ip> | jq -r '[.color.red, .color.green, .color.blue] | max as $max | "\(.[0] * 255 / $max * <brightness> | round) \(.[1] * 255 / $max * <brightness> | round) \(.[2] * 255 / $max * <brightness> | round)"')

It's not the prettiest thing (and you can probably make it shorter), but it should be sufficient for use in a script.

**Comment by 0rTiN** [comment]
Okay, thx for your fast feedback. I will go that way!

**Comment by 0rTiN** [comment]
Ok thx for your fast feedback. I will go that way. It will be sufficient for my needs.

**Comment by kevindevm** [comment]
@jangxx 
> sing jq you could have a bash oneliner like this however:

can i ask what does max represent?
whats the math to change the colors like 
R *255 / x * brightness ??

**Comment by kevindevm** [comment]
> I don't understand your question, sorry.
yet i got the awnser, thanks !
so i wanted to know the current brightness
it was as easy as  `100/(255/max(R,G,B))`
... thanks again!
