### ISSUE TITLE
Create typescript types for the lib

### ISSUE THREAD

**Issue by skoky** [jangxx/node-magichome#33]
It would be very useful to have typescript types file for the library. Thanks

**Comment by jangxx** [comment]
I don't personally use TypeScript (yet), so creating a definition file is pretty low priority for me right now.

I have documented most methods with JsHint however and was under the impression that TS can also use those comments as type definitions? Otherwise you are of course welcome to take a crack at it yourself and send a PR; I'm always happy to merge them.

**Comment by jangxx** [comment]
Thanks to the contribution of @z81 we now have full typescript types! They are included in version 2.7.1.
