### ISSUE TITLE
Works with blocked internet connection to the light?

### ISSUE THREAD

**Issue by FrankZZ** [jangxx/node-magichome#38]
Hi,

First of all- great project! Looking forward to using it & contributing to it.
I'm planning to buy an OFFDARKS ceiling light: 
https://www.aliexpress.com/item/4000385532059.html
I'm assuming this light will work with this library as it's also using the Magic Home app.

I was just wondering if this library keeps working when I block internet access for the light in my router.
Do you expect that this library will still be able to control the light? I know it's using a LAN connection, but still- maybe it requires the lamp to be connected to the internet?

**Comment by jangxx** [comment]
This library never communicates with any servers outside your own network, neither for discovery nor for control, so it _should_ work without issues.

I have seen newer versions of the Magic Home app require an account (and therefore connection to the internet) to set up new lights, so you might have to do the initial setup with the light connected to the internet.

It is also entirely possible that there is a new generation of Magic Home lights that _exclusively_ work via the internet. I have personally not seen them or heard of them, but I can't make any promises. That being said, I think you should be able to buy and use this without issues since it seems to be just an LED strip wrapped in a circle and put into a plastic case and not some special new category of light that would warrant breaking support for the local network connectivity.

**Comment by FrankZZ** [comment]
Thanks @jangxx for your quick reply. I ordered it & will report back how it went. 
If it does need constant internet- it's a pity but then that's just the way it is.

**Comment by jangxx** [comment]
Closed due to inactivity. Also since I now own one of the newest controllers, I can definitely say that they still work without an active internet connection.
