### ISSUE TITLE
light.setColor(r,g,b) sets ww to 100%

### ISSUE THREAD

**Issue by jghaanstra** [jangxx/node-magichome#4]
When using the light.setColor method on a RGBW LED strip using a Magic Home RGBW controller, the (warm) white setting is automatically set to 100%. Is this intended behaviour? I would assume only the RGB LED's would change to the given color and not also change the white leds.

**Comment by jangxx** [comment]
You are right, this is not intended behavior, it is just a side effect of always having to set every value.

I'm kind of surprised however, as the default setting should set the WW bytes to 0. They are only set to 0xFF if the characteristic ww_min_0 is set to false, which (if I recall correctly) was required to get the controller to accept the command on one of my controllers.

According to [this guy](https://github.com/vikstrous/zengge-lightcontrol), the first of the "magic bytes" is a boolean indicating whether to use the warm-white value, which is set to true (0xF0) by default. You can try to set the value to false (0x0F) and see if the problem persists:

    let control = new Control("address", { set_color_magic_bytes: [ 0x0f, 0x0f ] } );

Unfortunately I don't have a controller with a white strip connected to then, so if this doesn't work I can't help you any further. If you want to experiment however, you're welcome to send a pull request dealing with this problem by figuring out the magic bytes or maybe by writing a working `setWW(white, callback)` method.

**Comment by jghaanstra** [comment]
You are right, I was messing with the characteristics and appearantly left ww_min_0 set to false. Changed it to true and now it works as expected.

**Comment by jghaanstra** [comment]
@jangxx What has happened to the set_color_magic_bytes characteristic in the latest release? I'm troubleshooting an issue with the RGBWW device linked below and it does not seem to respond on the set color commands. I wanted to check if setting the set_color_magic_bytes to true (0xf0) would make a difference but is seems this is not available anymore. Do you have a reason why this has been removed. Btw, device model of the device below is HF-LPB100-ZJ200.

https://nl.aliexpress.com/item/DC12-24V-4A-5CH-RGB-WW-CW-LED-WIFI-Controller-IOS-Android-Smart-Link-Timer-Muziek/32850751889.html?spm=a2g0s.9042311.0.0.3da24c4dx44dNB

**Comment by jangxx** [comment]
>Do you have a reason why this has been removed.

Yes; I looked at the python code again, and as it turns out, the meaning of these "magic bytes" has been revealed. The second byte `0x0F` is a command terminator and setting it to any other value makes no sense. The first byte is an inverted bitmask, where `0xF0` sets only the colors, `0x0F` only the white value and `0x00` sets both. Since this command is only implemented in a single method `setColorAndWarmWhite`, which always sets both values, I saw no reason in having these values user settable anymore. Also, most controllers don't support this masking anyway (I know none of my controllers do), which was an additional reason. The whole idea of the characteristics in general came from a place of missing understanding, and now that we know more, they are just not necessary anymore.

Now, if you try running the python tool and it works where this library doesn't, it means you have hit an edge case I kind of expected, but ignored nevertheless. Apparently, there are some devices, where masking out the colors is actually possible and required. These devices have the type `0x25`. If you want to know the type of your device, just set the `log_all_received` option to `true` and run `queryState`. The first byte you receive tells you the type and normally it is either `0x04`, `0x33` or `0x81`. To work around this issue, you can try using `setColorAndWarmWhite` and setting at least one of the colors and the white value to something larger than 0. If that doesn't work I can try to port the additional functionality as well, but I'm pretty sure that this is not actually needed.

**Comment by jghaanstra** [comment]
Thanx for the elaborate response. I'll mess around some more with these instructions.
