### ISSUE TITLE
node cli.js setrgbww 192.168.2.50 50 30 20 1 1 returns success but no change on light

### ISSUE THREAD

**Issue by nospam2k** [jangxx/node-magichome#44]
Title pretty much says everything. I've tried other numbers for various rgbww values with same result.

node cli.js turnon 192.168.2.50 works

Same results with all other white and color setting commands.

Daybetter bulb

**Comment by jangxx** [comment]
Can you give me some more info on the specific light/controller you have (e.g. by telling me the output of `node cli.js discover`)? Does the light actually support both cold and warm white?

The "success" message is pretty misleading, since the tool has no idea if the command actually succeeded or not. It merely says that the command has been sent successfully, not that it has been received or that the light actually reacted.

**Comment by nospam2k** [comment]
discover returns nothing. Query returns: {"type":53,"on":true,"mode":"color","pattern":null,"speed":86.66666666666667,"color":{"red":0,"green":0,"blue":0},"warm_white":255,"cold_white":0}

The light does support cold and warm white as well as colors.

Here is an amazon link: https://smile.amazon.com/gp/product/B09FK4JRB6/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by jangxx** [comment]
But it doesn't support both at the same time. Try

`magic-home --masks --cw_support color 192.168.2.50 255 0 0` to set it to red

and

`magic-home --masks --cw_support whites 192.168.2.50 255 0` to set it to fully warm white.

The `--masks` option is important here, since the light can't set both at the same time (unlike LED strip controllers) and the `--cw_support` is needed to send different buffers that light with cold white support need.

**Comment by nospam2k** [comment]
node cli.js --masks color 192.168.2.50 255 0 0 - nothing.

I know that the Amazon info says RGBW but here is a shot of the bulb. Looks like RGBWW(?) Also the marking.

![PXL_20220720_180507909](https://user-images.githubusercontent.com/1284287/180052478-10d8faa6-6a75-4912-8b10-edef352db315.jpeg)

**Comment by jangxx** [comment]
I edited my comment. Try it with `--cw_support` and if that doesn't work leave out the `--masks` parameter again.

**Comment by nospam2k** [comment]
Ahh!!! --cw_support worked with --masks but not alone. Thx for the quick responses!

**Comment by nospam2k** [comment]
@jangxx I know this isn't your problem, but I've been banging my head trying to figure this out for an hour, hoping 2nd eyes may see something easy. If not, no worries. Here's my code:

```
const { Control } = require('magic-home'); // nodejs
const { Control } = global.get('magicHome'); // node-red (setup in settings.js)

const c = new Control('192.168.2.50', {
  log_all_received: false,
  apply_masks: true,
  ack: { power: true, color: false, pattern: false, custom_pattern: false },
  connect_timeout: null,
  command_timeout: 1000,
  cold_white_support: true
});

c.setColor(50, 30, 255).then(success =>
{
  console.log(success);
}).catch(err => {
  return console.log("Error:", err.message);
});
```

This works fine when I run from node, but I get TypeError: `[object Object]` is not an Option Object in node-red. I'm trying to avoid using node red nodes if possible. I have tons of node code in node red that works ok using global.get('module').

I guess what I'm really after is there another way to add options as individual variables rather than as an Object?

**Comment by nospam2k** [comment]
Got it! (not ideal but works) I dumped "c" and found that I can use c._options {}. That worked
